### ISSUE TITLE
Retire flatcar org?

### ISSUE THREAD

**Issue by ahrkrak** [flatcar-rails/flatcar#12]
Hey folks, it looks like this org is unused, and only holds a fork from the CenturyLinkLabs/flatcar project, which is equally quiet (since 6 years).
I work on a very active Linux project called Flatcar (github.com/flatcar-linux) and it would help our community a lot to be able to have the simpler github URL.
Would you be open to retiring/renaming this org?
Not sure who the owner is, so I'm tagging the two main contributors @rheinwein @dharmamike

**Comment by rheinwein** [comment]
Hey, we'd be happy to retire this org and pass it over you to folks so flatcar-linux can use it. @dharmamike and I will clean this up over the next couple days and then add you to the org so you can take over as owner and take it forward. Cheers!

**Comment by rheinwein** [comment]
Hey @ahrkrak you should have an invite for a nice clean flatcar org. If there is some swag left from KubeCon @dharmamike and I would love a Flatcar shirt :)

**Comment by ahrkrak** [comment]
Perfect! Thank you both. We're working out the move now. Can you send me your addresses and t-shirt sizes to andrew.randall@microsoft.com?
